// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var active, doRotation, panels, print;
    panels = $('.slideshow').find('li');
    active = 0;
    print = function(message) {
      return console.log(message);
    };
    print(panels);
    panels.css({
      left: '-400px'
    });
    $(panels[0]).css({
      left: '0px'
    });
    doRotation = function() {
      var next;
      next = active === (panels.length - 1) ? 0 : active + 1;
      $(panels[active]).animate({
        left: '-400px'
      });
      $(panels[next]).css({
        left: '400px'
      });
      $(panels[next]).animate({
        left: '0px'
      }, 1000);
      active = next;
      return print('rotate');
    };
    return window.setInterval(doRotation, 4000);
  });

}).call(this);
