// Generated by CoffeeScript 1.8.0
(function() {
  window.onload = function() {
    var output;
    output = document.getElementById('output');
    return output.appendChild(document.createTextNode('Time for coffee'));
  };

}).call(this);
